const url = "../../assets";

export const images = {
  category_agrimensor: require(`${url}/categorias/agrimensor.png`),
  category_albanil: require(`${url}/categorias/albanil.png`),
  category_carpintero: require(`${url}/categorias/albanil.png`),
  category_cerrajero: require(`${url}/categorias/cerrajero.png`),
  category_cerrajero: require(`${url}/categorias/cerrajero.png`),
  category_cuidador: require(`${url}/categorias/cuidador.png`),
  category_electricista: require(`${url}/categorias/electricista.png`),
  category_fumigador: require(`${url}/categorias/fumigador.png`),
  category_herrero: require(`${url}/categorias/herrero.png`),
  category_jardinero: require(`${url}/categorias/jardinero.png`),
  category_limpieza: require(`${url}/categorias/limpieza.png`),
  category_pintor: require(`${url}/categorias/pintor.png`),
  category_plomero: require(`${url}/categorias/plomero.png`),
  icon_jardinero: require(`${url}/iconos/jardinero.png`),
  icon_marketing: require(`${url}/iconos/marketing.png`),
  icon_plomero: require(`${url}/iconos/plomero.png`),
  icon_defaultImage: require(`${url}/iconos/defaultImage.png`),
  icon_covid: require(`${url}/iconos/covid.png`),
  icon_whatsapp: require(`${url}/iconos/whatsapp.png`),
  icon_telefono: require(`${url}/iconos/telefono.png`),
  icon_sms: require(`${url}/iconos/sms.png`),
  user_andres: require(`${url}/usuarios/andres.jpg`),
  user_alejandro: require(`${url}/usuarios/alejandro.jpg`),
  user_dami: require(`${url}/usuarios/dami.jpg`),
  user_marce: require(`${url}/usuarios/marce.jpg`),
  user_mariano: require(`${url}/usuarios/mariano.jpg`),
  user_nahuel: require(`${url}/usuarios/nahuel.jpg`),
  user_nico: require(`${url}/usuarios/nico.jpg`),
  sugerencias_a: require(`${url}/sugerencias/a.png`),
  sugerencias_b: require(`${url}/sugerencias/b.png`),
  sugerencias_c: require(`${url}/sugerencias/c.png`),
  trabajadores_a: require(`${url}/trabajadores/a.png`),
  trabajadores_b: require(`${url}/trabajadores/b.png`),
  trabajadores_c: require(`${url}/trabajadores/c.png`),
  proyectos_a: require(`${url}/proyectos/a.png`),
  proyectos_b: require(`${url}/proyectos/b.png`),
  proyectos_c: require(`${url}/proyectos/c.png`),
  flagDefault: require(`${url}/flagdefault.png`),
  portada: require(`${url}/portada.png`),
  icon: require(`${url}/icon.png`),
};
