export { default as Logotipo } from './logotipo';
export { default as Logo } from './logo';
export { default as Key } from './key';
export { default as Google } from './google';
export { default as Facebook } from './facebook';
export { default as Candado} from './candado'
export { default as SearchJob } from './searchJob'
export { default as Share } from './share'
export { default as WritePost } from './writePost'
export { default as Warning } from './warning'
export { default as Cross } from './cross'
export { default as Email } from './email';
export { default as Check } from './check'
export { default as Hide } from './hide';
export { default as Show } from './show';
export { default as BackArrow } from './backArrow';
export { default as DownArrow } from './downArrow';
export { default as PersonalData } from './personalData';
export { default as Man } from './man';
export { default as Woman } from './woman';
export { default as Camera } from './camera';
export { default as Galery } from './galery';
export { default as Reloj } from './reloj'
export { default as ErrorEmail } from './errorMail'
export { default as Estrellas } from './estrellas'
export { default as SMS } from './sms'
export { default as Terms } from './terms'
export { default as Home } from './home'
export { default as Store } from './store'
export { default as Contacts } from './contacts'

export { default as ChangeMode } from './changeMode'
export { default as ShareAction } from './shareAction'
export { default as GiveFeedback } from './giveFeedback'
export { default as Settings } from './settings'
export { default as SignOut } from './SignOut'
export { default as Pedidos } from './pedidos'
export { default as Search } from './search'
export { default as ArrowPush } from './arrowPush'
